repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: flake8
      entry: flake8 --ignore=E203
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: /home/risitop/.local/share/virtualenvs/transmorph_local-9qMrZcwm/bin/pytest
        language: python
        pass_filenames: false
        always_run: true
        additional_dependencies:
            - pynndescent
